### ISSUE TITLE
thematic_rmd() doesn't work well with runtime: shiny

### ISSUE THREAD

**Issue by cpsievert** [rstudio/thematic#86]
Note how the plot doesn't pick up the main colors

````yaml
---
output: 
  html_document:
    theme:
      bg: "#101010"
      fg: "#FDF7F7"
runtime: shiny
---

```{r setup, include=FALSE}
thematic::thematic_rmd()
bslib::bs_themer()
```

## R Markdown

Some inline `code`.

```{r cars, echo = TRUE}
renderPlot({
  plot(pressure)
})
```
````
